services:
  - type: web
    name: soma-flask-api
    env: python
    buildCommand: |
      apt-get update && apt-get install -y tesseract-ocr tesseract-ocr-kor
      pip install -r requirements.txt
    startCommand: python app.py